In [1]:
import pickle
import collections
import pandas as pd

In [5]:
msck_="data/msc_100k.csv"
mscw_="data/msc_weekly.csv"
crmk_="data/crm_100k.csv"
crmw_="data/crm_weekly.csv"
tack_="data/tac_100k.csv"
tacw_="data/tac_weekly.csv"

In [26]:
pd.low_memory=False
msck = pd.read_table(open(msck_,encoding='utf-8'),header=None,low_memory=False,sep=';')
mscw = pd.read_table(open(mscw_,encoding='utf-8'),header=None,low_memory=False,sep=';')
crmk = pd.read_table(open(crmk_,encoding='utf-8'),header=None,low_memory=False,sep=';')
crmw = pd.read_table(open(crmw_,encoding='utf-8'),header=None,low_memory=False,sep=';')
tack = pd.read_table(open(tack_,encoding='utf-8'),header=None,low_memory=False,sep=';')
tacw = pd.read_table(open(tacw_,encoding='utf-8'),header=None,low_memory=False,sep=';')

In [28]:
crmw

,0,1,2,3,4,5,6,7,8,9
0,dataset,subscriber,zip,sex,age,magan,uzleti,magenta_1,arpu,sim_4g
1,10.03,5846BF34,1147,M,36,1,0,0,3,1
2,10.03,585949AE,1087,M,53,1,0,0,1,1
3,10.03,582837BD,1215,M,49,1,0,0,1,1
4,10.03,581FF2EC,1022,F,38,1,0,0,5,1
5,10.03,58241EFB,1186,F,49,1,0,0,2,1
6,10.03,581F6BB3,1193,F,57,1,0,0,1,1
7,10.03,58101D3A,1108,M,21,1,0,0,1,1
8,10.03,5802462E,1123,F,56,1,0,0,1,0
9,10.03,584A3C56,1087,NaN,NaN,0,1,0,1,1
10,10.03,583E42C5,1051,NaN,NaN,0,1,0,5,1
11,10.03,582888D9,1161,NaN,NaN,0,1,0,2,1
12,10.03,585E8846,1013,F,46,1,0,0,2,1
13,10.03,584FB3AC,1224,F,61,1,0,0,2,1
14,10.03,580CBFC8,1173,F,25,1,0,0,2,1
15,10.03,584012B0,1149,F,29,1,0,0,3,1
16,10.03,583C417A,1034,F,71,1,0,0,1,1
17,10.03,5840E88B,1053,M,45,1,0,0,3,1
18,10.03,580310E3,1103,NaN,NaN,0,1,0,1,1
19,10.03,581EA1BD,1164,NaN,NaN,0,1,0,2,1
20,10.03,580A327D,1138,NaN,NaN,0,1,0,3,1
21,10.03,5842FF71,1039,M,66,1,0,0,2,0
22,10.03,580BF672,1163,F,56,1,0,0,2,1
23,10.03,58043563,1124,NaN,NaN,0,1,0,1,1
24,10.03,581E13DB,1453,NaN,NaN,0,1,0,1,1
25,10.03,583FADA6,1093,F,53,1,0,0,1,1
26,10.03,582EF6B4,1215,M,49,1,0,0,1,1
27,10.03,584A131C,1071,F,25,1,0,0,3,1
28,10.03,581FC47F,1085,NaN,NaN,0,1,0,1,1
29,10.03,5826089F,1082,M,30,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...
9975,10.09,584F6455,1151,F,26,1,0,0,1,1
9976,10.09,580220AF,1122,M,47,1,0,0,2,0
9977,10.09,5808F32C,1042,NaN,NaN,1,1,0,1,0
9978,10.09,58434702,1113,F,62,1,0,0,1,0
9979,10.09,580E1873,1163,NaN,NaN,1,1,0,4,1
9980,10.09,58112DFE,1124,M,56,1,0,0,1,0
9981,10.09,58485247,1113,M,47,1,0,0,1,1
9982,10.09,583A11D8,1157,F,39,1,0,0,1,1
9983,10.09,582CC204,1062,NaN,NaN,0,1,0,1,1
9984,10.09,582D28CF,1117,M,33,1,0,0,1,1
9985,10.09,584FF0F3,1211,M,42,1,0,0,1,0
9986,10.09,58113B9A,1091,F,33,1,0,0,1,1
9987,10.09,5858FB78,1051,NaN,NaN,0,1,0,1,1
9988,10.09,580EDFCA,1103,NaN,NaN,0,1,0,1,1
9989,10.09,580A1F0D,1117,NaN,NaN,0,1,0,1,1
9990,10.09,5840177D,1133,F,80,1,0,0,2,1
9991,10.09,580C9CF5,1212,M,41,1,0,0,1,0
9992,10.09,583525BA,1215,M,49,1,0,0,1,0
9993,10.09,585AB0D7,1211,M,65,1,0,0,1,0
9994,10.09,580D84F6,1012,NaN,NaN,1,1,0,5,1
9995,10.09,584ACBB2,1211,M,42,1,0,0,1,0
9996,10.09,58297BB5,1195,F,24,1,0,0,1,1
9997,10.09,581A255B,1101,NaN,NaN,0,1,0,5,1
9998,10.09,581EE723,1453,NaN,NaN,0,1,0,1,1
9999,10.09,5830F902,1162,M,25,1,0,0,1,1
10000,10.09,580F18AB,1042,NaN,NaN,1,1,0,1,1
10001,10.09,5802E683,1104,F,38,1,0,0,4,1
10002,10.09,5818C6BA,1042,NaN,NaN,1,1,0,1,0
10003,10.09,58290391,1026,M,35,1,0,0,1,1
10004,10.09,581FAE66,1015,F,54,1,0,0,1,1

In [29]:
crmw[0][0]

'dataset'